title: Joah Gerstenberg
description: Software Engineer building user experiences that connect people with the world around them
author: Joah Gerstenberg
email: me@joahg.com
url: "https://joahg.dev"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  posts:
    output: true
    permalink: /:title/
